#!/bin/sh

selection=$(
  swaymsg -t get_tree |
    jq -r '.. | objects | select(.type? == "con" and .pid? != null and .name? != null) | "\(.id)\t\(.name)"' |
    wmenu -i -p "window:"
) || exit 0

con_id=${selection%%	*}
[ -n "$con_id" ] && swaymsg "[con_id=$con_id] focus"
